/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Habit {
  'id' : HabitId,
  'creator' : UserId,
  'targetFrequency' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'lastUpdated' : bigint,
  'description' : [] | [string],
  'soundEnabled' : boolean,
  'reminderTime' : [] | [bigint],
  'streakCount' : bigint,
}
export interface HabitEntryInput {
  'targetFrequency' : bigint,
  'name' : string,
  'description' : [] | [string],
  'soundEnabled' : boolean,
  'reminderTime' : [] | [bigint],
}
export type HabitId = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'completeHabit' : ActorMethod<[HabitId], undefined>,
  'createHabit' : ActorMethod<[HabitEntryInput], HabitId>,
  'deleteHabit' : ActorMethod<[HabitId], undefined>,
  'getAllHabits' : ActorMethod<[], Array<Habit>>,
  'getAllHabitsWithStreaks' : ActorMethod<[], Array<[Habit, Array<bigint>]>>,
  'getHabit' : ActorMethod<[HabitId], Habit>,
  'getHabitWithStats' : ActorMethod<[HabitId], [Habit, Array<bigint>]>,
  'getRecentCompletions' : ActorMethod<[HabitId, bigint], Array<bigint>>,
  'updateHabit' : ActorMethod<[HabitId, HabitEntryInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];