/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HabitId = IDL.Int;
export const HabitEntryInput = IDL.Record({
  'targetFrequency' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'soundEnabled' : IDL.Bool,
  'reminderTime' : IDL.Opt(IDL.Int),
});
export const UserId = IDL.Principal;
export const Habit = IDL.Record({
  'id' : HabitId,
  'creator' : UserId,
  'targetFrequency' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'lastUpdated' : IDL.Int,
  'description' : IDL.Opt(IDL.Text),
  'soundEnabled' : IDL.Bool,
  'reminderTime' : IDL.Opt(IDL.Int),
  'streakCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'completeHabit' : IDL.Func([HabitId], [], []),
  'createHabit' : IDL.Func([HabitEntryInput], [HabitId], []),
  'deleteHabit' : IDL.Func([HabitId], [], []),
  'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getAllHabitsWithStreaks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Habit, IDL.Vec(IDL.Int)))],
      ['query'],
    ),
  'getHabit' : IDL.Func([HabitId], [Habit], ['query']),
  'getHabitWithStats' : IDL.Func(
      [HabitId],
      [Habit, IDL.Vec(IDL.Int)],
      ['query'],
    ),
  'getRecentCompletions' : IDL.Func(
      [HabitId, IDL.Nat],
      [IDL.Vec(IDL.Int)],
      ['query'],
    ),
  'updateHabit' : IDL.Func([HabitId, HabitEntryInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HabitId = IDL.Int;
  const HabitEntryInput = IDL.Record({
    'targetFrequency' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'soundEnabled' : IDL.Bool,
    'reminderTime' : IDL.Opt(IDL.Int),
  });
  const UserId = IDL.Principal;
  const Habit = IDL.Record({
    'id' : HabitId,
    'creator' : UserId,
    'targetFrequency' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'description' : IDL.Opt(IDL.Text),
    'soundEnabled' : IDL.Bool,
    'reminderTime' : IDL.Opt(IDL.Int),
    'streakCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'completeHabit' : IDL.Func([HabitId], [], []),
    'createHabit' : IDL.Func([HabitEntryInput], [HabitId], []),
    'deleteHabit' : IDL.Func([HabitId], [], []),
    'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getAllHabitsWithStreaks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Habit, IDL.Vec(IDL.Int)))],
        ['query'],
      ),
    'getHabit' : IDL.Func([HabitId], [Habit], ['query']),
    'getHabitWithStats' : IDL.Func(
        [HabitId],
        [Habit, IDL.Vec(IDL.Int)],
        ['query'],
      ),
    'getRecentCompletions' : IDL.Func(
        [HabitId, IDL.Nat],
        [IDL.Vec(IDL.Int)],
        ['query'],
      ),
    'updateHabit' : IDL.Func([HabitId, HabitEntryInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };