/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type HabitId = bigint;
export type UserId = Principal;
export interface HabitEntryInput {
    targetFrequency: bigint;
    name: string;
    description?: string;
    soundEnabled: boolean;
    reminderTime?: bigint;
}
export interface Habit {
    id: HabitId;
    creator: UserId;
    targetFrequency: bigint;
    name: string;
    createdAt: bigint;
    lastUpdated: bigint;
    description?: string;
    soundEnabled: boolean;
    reminderTime?: bigint;
    streakCount: bigint;
}
export interface backendInterface {
    completeHabit(habitId: HabitId): Promise<void>;
    createHabit(habitData: HabitEntryInput): Promise<HabitId>;
    deleteHabit(habitId: HabitId): Promise<void>;
    getAllHabits(): Promise<Array<Habit>>;
    getAllHabitsWithStreaks(): Promise<Array<[Habit, Array<bigint>]>>;
    getHabit(habitId: HabitId): Promise<Habit>;
    getHabitWithStats(habitId: HabitId): Promise<[Habit, Array<bigint>]>;
    getRecentCompletions(habitId: HabitId, days: bigint): Promise<Array<bigint>>;
    updateHabit(habitId: HabitId, update: HabitEntryInput): Promise<void>;
}
import type { Habit as _Habit, HabitEntryInput as _HabitEntryInput, HabitId as _HabitId, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeHabit(arg0: HabitId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeHabit(arg0);
            return result;
        }
    }
    async createHabit(arg0: HabitEntryInput): Promise<HabitId> {
        if (this.processError) {
            try {
                const result = await this.actor.createHabit(to_candid_HabitEntryInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHabit(to_candid_HabitEntryInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteHabit(arg0: HabitId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHabit(arg0);
            return result;
        }
    }
    async getAllHabits(): Promise<Array<Habit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHabits();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHabits();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHabitsWithStreaks(): Promise<Array<[Habit, Array<bigint>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHabitsWithStreaks();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHabitsWithStreaks();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabit(arg0: HabitId): Promise<Habit> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabit(arg0);
                return from_candid_Habit_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabit(arg0);
            return from_candid_Habit_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabitWithStats(arg0: HabitId): Promise<[Habit, Array<bigint>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabitWithStats(arg0);
                return [
                    from_candid_Habit_n4(this._uploadFile, this._downloadFile, result[0]),
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabitWithStats(arg0);
            return [
                from_candid_Habit_n4(this._uploadFile, this._downloadFile, result[0]),
                result[1]
            ];
        }
    }
    async getRecentCompletions(arg0: HabitId, arg1: bigint): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentCompletions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentCompletions(arg0, arg1);
            return result;
        }
    }
    async updateHabit(arg0: HabitId, arg1: HabitEntryInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHabit(arg0, to_candid_HabitEntryInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHabit(arg0, to_candid_HabitEntryInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Habit_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Habit): Habit {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _HabitId;
    creator: _UserId;
    targetFrequency: bigint;
    name: string;
    createdAt: bigint;
    lastUpdated: bigint;
    description: [] | [string];
    soundEnabled: boolean;
    reminderTime: [] | [bigint];
    streakCount: bigint;
}): {
    id: HabitId;
    creator: UserId;
    targetFrequency: bigint;
    name: string;
    createdAt: bigint;
    lastUpdated: bigint;
    description?: string;
    soundEnabled: boolean;
    reminderTime?: bigint;
    streakCount: bigint;
} {
    return {
        id: value.id,
        creator: value.creator,
        targetFrequency: value.targetFrequency,
        name: value.name,
        createdAt: value.createdAt,
        lastUpdated: value.lastUpdated,
        description: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.description)),
        soundEnabled: value.soundEnabled,
        reminderTime: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.reminderTime)),
        streakCount: value.streakCount
    };
}
function from_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Habit, Array<bigint>]): [Habit, Array<bigint>] {
    return [
        from_candid_Habit_n4(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Habit>): Array<Habit> {
    return value.map((x)=>from_candid_Habit_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Habit, Array<bigint>]>): Array<[Habit, Array<bigint>]> {
    return value.map((x)=>from_candid_tuple_n9(_uploadFile, _downloadFile, x));
}
function to_candid_HabitEntryInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HabitEntryInput): _HabitEntryInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    targetFrequency: bigint;
    name: string;
    description?: string;
    soundEnabled: boolean;
    reminderTime?: bigint;
}): {
    targetFrequency: bigint;
    name: string;
    description: [] | [string];
    soundEnabled: boolean;
    reminderTime: [] | [bigint];
} {
    return {
        targetFrequency: value.targetFrequency,
        name: value.name,
        description: value.description ? candid_some(value.description) : candid_none(),
        soundEnabled: value.soundEnabled,
        reminderTime: value.reminderTime ? candid_some(value.reminderTime) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
